#!/usr/bin/env python3
"""Fit a configured TESS transit and write reusable numerical products."""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
import os
from pathlib import Path
import re
import sys

os.environ.setdefault("MPLBACKEND", "Agg")

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import matplotlib.pyplot as plt

import config
from dataio.tess_photometry import (
    TessTransitFitConfig,
    fit_tess_transit_to_bandpass_constraint,
    save_tess_fit_artifacts,
)
from plotting.style import save_figure_pdf
from plotting.tess_transit import (
    plot_lightcurve_overview,
    plot_posterior_corner,
    plot_transit_fit,
)


def _slug(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--planet", required=True, choices=sorted(config.TESS_TRANSIT_CASES))
    parser.add_argument(
        "--sector",
        type=int,
        action="append",
        help="Restrict the fit to a sector; repeat for multiple sectors.",
    )
    parser.add_argument("--mlexo-root", type=Path, help="Path to the local mlexo checkout.")
    parser.add_argument("--burnin-steps", type=int, default=150)
    parser.add_argument("--production-steps", type=int, default=300)
    parser.add_argument("--processes", type=int, default=1)
    parser.add_argument("--seed", type=int, default=123)
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=PROJECT_ROOT / "output" / "tess_transit",
        help="Root directory for timestamped fit products.",
    )
    return parser


def main() -> None:
    args = build_parser().parse_args()
    case = dict(config.TESS_TRANSIT_CASES[args.planet])
    fit_config = TessTransitFitConfig(
        **case,
        sectors=tuple(args.sector) if args.sector else None,
        mlexo_root=args.mlexo_root,
        emcee_burnin_steps=args.burnin_steps,
        emcee_production_steps=args.production_steps,
        emcee_use_pool=args.processes > 1,
        emcee_n_processes=args.processes,
        random_seed=args.seed,
        planet_name=args.planet,
        reference="config.TESS_TRANSIT_CASES",
        note="Generated by scripts/run_tess_transit.py",
    )
    result = fit_tess_transit_to_bandpass_constraint(fit_config)
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    run_dir = args.output_dir / _slug(args.planet) / timestamp
    save_tess_fit_artifacts(result, run_dir)

    figures = {
        "lightcurve_overview.pdf": plot_lightcurve_overview(
            result.dataset,
            period_d=fit_config.period_d,
            t0_btjd=fit_config.t0_btjd,
            target=fit_config.target,
        ),
        "transit_fit.pdf": plot_transit_fit(result),
        "posterior_corner.pdf": plot_posterior_corner(result),
    }
    for filename, figure in figures.items():
        if figure is not None:
            save_figure_pdf(figure, run_dir / filename)
            plt.close(figure)
    print(run_dir)


if __name__ == "__main__":
    main()
